(****************************************
*                                       *
*     MODULA-2 Multi-Pass Compiler      *
*     ****************************      *
*                                       *
*     Implementation for Lilith         *
*                                       *
*                                       *
*     MCBase:                           *
*                                       * 
*     private part of the common base   *
*     of the Modula-2 compiler          *
*                                       * 
*     Version C19 of 22.07.82           *
*                                       *
*     Institut fuer Informatik          *
*     ETH-Zuerich                       *
*     CH-8092 Zuerich                   *
*                                       *
****************************************)

IMPLEMENTATION MODULE MCBase;   (* LG *)

  IMPORT CompFile, Storage, MCPublic;

  (* empty implementation *)

END MCBase.
