(****************************************
*                                       *
*     MODULA-2 Multi-Pass Compiler      *
*     ****************************      *
*                                       *
*     Implementation for Lilith         *
*                                       *
*                                       *
*     MCSymFileDefs:                    *
*                                       * 
*     definition of symbols             *
*     used on symbol files              *
*                                       * 
*     Version C19 of 19.04.82           *
*                                       *
*     Institut fuer Informatik          *
*     ETH-Zuerich                       *
*     CH-8092 Zuerich                   *
*                                       *
****************************************)

IMPLEMENTATION MODULE MCSymFileDefs;  (* LG *)

  (* empty implementation *)

END MCSymFileDefs.
